site_name: tooldiscovery
site_description: Documentation for tooldiscovery
repo_name: jonwraymond/tooldiscovery
repo_url: https://github.com/jonwraymond/tooldiscovery
edit_uri: edit/main/docs/
docs_dir: docs
nav:
  - Home: index.md
  - Design Notes: design-notes.md
  - User Journey: user-journey.md
theme:
  name: material
